### ISSUE TITLE
Weopon changing

### ISSUE THREAD

**Issue by bamooxa** [SimplyJpk/TF2-JumpTimer#2]
May want to reconsider when weopon changing cancels a run.
Examples.
- swapping to shotgun when on a button level will cancel
- Swapping from original to stock or cow mangler, some jumps are easier with different launchers. Up to you if you want to keep that freedom.
- Swapping pipe launcher for iron bomber. Iron bomber is easier to jump with.

Generally, people forget to edit their load out before jumping. It's disappointing realizing the time's cancelled half way through a map.

**Comment by SimplyJpk** [comment]
Will be fixed next time I push. Will only stop run if changed weapon is to a restricted weapon.
